spring:
  application:
    name: Reparieren Statt Wegwerfen - Backoffice
  ai:
    openai:
      chat:
        model: gpt-5.4-mini
  threads:
    virtual:
      enabled: true
springdoc:
  default-produces-media-type: application/json