--liquibase formatted sql
--changeset fabian:2026-05-21-data context:businesspartner

INSERT INTO business_partner_address_country (business_partner_address_country_id, name, code, sort_order)
VALUES (1, 'Österreich', 'AT', 1),
       (2, 'Deutschland', 'DE', 2),
       (3, 'Albanien', 'AL', 3),
       (4, 'Andorra', 'AD', 4),
       (5, 'Belgien', 'BE', 5),
       (6, 'Bosnien und Herzegowina', 'BA', 6),
       (7, 'Bulgarien', 'BG', 7),
       (8, 'Dänemark', 'DK', 8),
       (9, 'Estland', 'EE', 9),
       (10, 'Finnland', 'FI', 10),
       (11, 'Frankreich', 'FR', 11),
       (12, 'Griechenland', 'GR', 12),
       (13, 'Irland', 'IE', 13),
       (14, 'Island', 'IS', 14),
       (15, 'Italien', 'IT', 15),
       (16, 'Kroatien', 'HR', 16),
       (17, 'Lettland', 'LV', 17),
       (18, 'Liechtenstein', 'LI', 18),
       (19, 'Litauen', 'LT', 19),
       (20, 'Luxemburg', 'LU', 20),
       (21, 'Malta', 'MT', 21),
       (22, 'Moldau', 'MD', 22),
       (23, 'Monaco', 'MC', 23),
       (24, 'Montenegro', 'ME', 24),
       (25, 'Niederlande', 'NL', 25),
       (26, 'Nordmazedonien', 'MK', 26),
       (27, 'Norwegen', 'NO', 27),
       (28, 'Polen', 'PL', 28),
       (29, 'Portugal', 'PT', 29),
       (30, 'Rumänien', 'RO', 30),
       (31, 'San Marino', 'SM', 31),
       (32, 'Schweden', 'SE', 32),
       (33, 'Schweiz', 'CH', 33),
       (34, 'Serbien', 'RS', 34),
       (35, 'Slowakei', 'SK', 35),
       (36, 'Slowenien', 'SI', 36),
       (37, 'Spanien', 'ES', 37),
       (38, 'Tschechien', 'CZ', 38),
       (39, 'Ukraine', 'UA', 39),
       (40, 'Ungarn', 'HU', 40),
       (41, 'Vatikanstadt', 'VA', 41),
       (44, 'Zypern', 'CY', 42);