--liquibase formatted sql
--changeset fabian:2026-05-21-data context:businesspartner

INSERT INTO business_partner_address_country (business_partner_address_country_id, name, code)
VALUES (1, 'Österreich', 'AT'),
       (2, 'Deutschland', 'DE'),
       (3, 'Albanien', 'AL'),
       (4, 'Andorra', 'AD'),
       (5, 'Belgien', 'BE'),
       (6, 'Bosnien und Herzegowina', 'BA'),
       (7, 'Bulgarien', 'BG'),
       (8, 'Dänemark', 'DK'),
       (9, 'Estland', 'EE'),
       (10, 'Finnland', 'FI'),
       (11, 'Frankreich', 'FR'),
       (12, 'Griechenland', 'GR'),
       (13, 'Irland', 'IE'),
       (14, 'Island', 'IS'),
       (15, 'Italien', 'IT'),
       (16, 'Kroatien', 'HR'),
       (17, 'Lettland', 'LV'),
       (18, 'Liechtenstein', 'LI'),
       (19, 'Litauen', 'LT'),
       (20, 'Luxemburg', 'LU'),
       (21, 'Malta', 'MT'),
       (22, 'Moldau', 'MD'),
       (23, 'Monaco', 'MC'),
       (24, 'Montenegro', 'ME'),
       (25, 'Niederlande', 'NL'),
       (26, 'Nordmazedonien', 'MK'),
       (27, 'Norwegen', 'NO'),
       (28, 'Polen', 'PL'),
       (29, 'Portugal', 'PT'),
       (30, 'Rumänien', 'RO'),
       (31, 'San Marino', 'SM'),
       (32, 'Schweden', 'SE'),
       (33, 'Schweiz', 'CH'),
       (34, 'Serbien', 'RS'),
       (35, 'Slowakei', 'SK'),
       (36, 'Slowenien', 'SI'),
       (37, 'Spanien', 'ES'),
       (38, 'Tschechien', 'CZ'),
       (39, 'Ukraine', 'UA'),
       (40, 'Ungarn', 'HU'),
       (41, 'Vatikanstadt', 'VA'),
       (44, 'Zypern', 'CY');